
# International Food Policy Research Institute


## 2024


1.IDRC (Senegal)

•	Description: Strengthening national capacities and policies for food systems analysis and transformation in Kenya, Ghana and Senegal; Analytical and capacity support project in Senegal

•	Outputs: Organization of learning event; Support to identification and co-development of training material; Contribution to research and evidence on Senegal's food system

2.MCF (Market/Youth/PHL)

•	Description: Knowledge generation related to drivers of food demand (cf. supermarkets, urbanization, consumer awareness) in food system development and transformation

•	Outputs: Data checking/preparation/compilation of selected countries; support to evidence generation

3.CGIAR Initiative on FCM (NORAD-funding WP5)

•	Description: Studying nexus of Fragility/Conflict/Migration in G5 Sahel countries based on secondary data in collaboration with WFP

•	Outputs: Checking/preparation/compilation of WFP-M&E data and ENSA-like datasets for selected countries; support to evidence generation

4.USAID-Niger

•	Description: Agri-food system and policy landscaping in Niger

•	Outputs: (complete this based on the expected outputs for the work that you are currently doing – perhaps check with John if not clear)

5.WFP-Chad

•	Description: Cost benefit analysis of WFP resilience interventions in Chad

•	Outputs: Checking/preparation/compilation of WFP-M&E data; support to evidence generation

6.WFP-Burundi

•	Description: Assessment of contribution of the WFP project PATSAB to livelihoods and food security of smallholder farmers and school children in Burundi

•	Outputs: Support to implementation of baseline study in targeted provinces (farmers and schools); support to evidence generation

## 2022 to 2023




## Strengthening Food Systems to Promote Increased Value Chain Employment Opportunities for Youth founded by the Mastercard Foundation

### Implications of urbanization, consumer awareness, and income trends on food systems development in Senegal

## Fragility, Conflict, and Migration Initiative

## Strengthening National Capacities and Policies for Food Systems Analysis and Transformation in Kenya, Ghana, and Senegal

## Agri-food system and policy landscaping in Niger

This proposal is to support the Niger Mission with an agri-food system and policy landscape analysis to better understand primary stakeholders, capacity gaps and the potential for various agri-food sectors to drive economic development in line with the following objectives:

1.  Mapping of Niger's agri-food system

<!-- -->

2.  Identify the major capacity gaps within the agricultural sector

<!-- -->

3.  Provide recommendations for areas of potential growth that might serve as a driver for economic development, poverty reduction, and resilience to shocks

<!-- -->

4.  Provide recommendations for how the capacity in the sector and business enabling environment might be improved

## Projet d'Appui à la transformation des Systèmes agro-alimentaires au Burundi (PATSAB)

-   Objectif général :

Contribuer de manière durable à la réduction de la pauvreté, à travers l'augmentation des revenus des petits exploitants agricoles, et à l'amélioration de la sécurité alimentaire et nutritionnelle des populations vulnérables, surtout les petits exploitants agricoles et leurs communautés

-   Objectifs spécifiques

1.  Renforcer les capacités de production des petits producteurs (y compris pour la production d'aliments à haute valeur nutritive), en améliorant leur organisation et accès aux facteurs de production

2.  Soutenir l'intégration des petits producteurs aux marchés de demande structurée dans le pays à travers l'accès aux marchés structurés et rémunérateurs

3.  Renforcer les capacités des ménages agricoles à adopter des pratiques alimentaires et nutritionnelles saines

-   Résultats attendus / Effets attendus

# International Organization for Migration (IOM)


## Does engaging in peer-to-peer awareness-raising have any effect on returnee migrants' mental health and psychosocial status? A pilot study from West Africa

[more](https://publications.iom.int/books/does-engaging-peer-peer-awarenessraising-have-any-effect-returnee-migrants-mental-health-and)

## Irregular Migration from West Africa: Robust Evaluation of Peer-to-peer Awareness-raising Activities in Four Countries

[more](https://publications.iom.int/books/irregular-migration-west-africa-robust-evaluation-peer-peer-awareness-raising-activities-four)


# French agricultural research and cooperation organization (CIRAD)

## Sustainable bioenergy for small agrifood enterprises in rural areas of West Africa - BIOSTAR

[more](https://www.cirad.fr/en/worldwide/cirad-worldwide/projects/biostar-project)

## Bioenergies and employment dynamics in food processing SMEs in West Africa

[more](https://econpapers.repec.org/paper/haljournl/hal-03704685.htm)
